# Generated by Django 3.1.7 on 2021-07-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='comment',
            new_name='description',
        ),
    ]
