# Generated by Django 3.1.7 on 2021-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210705_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
